# Generated by Django 4.1.7 on 2023-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_API', '0003_image_link_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link_expiration_time',
            field=models.DateTimeField(),
        ),
    ]
