# Generated by Django 4.1.7 on 2023-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_API', '0004_alter_image_link_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
