# Generated by Django 4.1.7 on 2023-03-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_API', '0005_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
    ]
