# Generated by Django 4.1.7 on 2023-03-08 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_API', '0007_alter_plan_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiration_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='link_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
